spring.application.name=stayhub-Country
server.port=8082
grpc.server.port=9092

spring.datasource.url=jdbc:h2:file:./data/testdb_Country
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console-Country

springdoc.api-docs.path=/api-docs-Country
springdoc.swagger-ui.path=/swagger-ui.html

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

logging.level.org.springframework=INFO
logging.level.com.Angelh0.stayhook=DEBUG
